### ISSUE TITLE
When user is email address, doesn't update when editing

### ISSUE THREAD

**Issue by dannyuk1982** [edalzell/statamic-profiler#14]
If users use email and not username to login, then using `email` as the field name in the profiler form means that it will populate the field, but won't update on save. Using `username` it works fine.

**Comment by edalzell** [comment]
it says this in the docs, I think this is expected?
```
If your login is set to email, then your email field should actually be a username field as that is what the user name is.
```

@dannyuk1982

**Comment by edalzell** [comment]
Working as documented. Please re-open if you disagree.
