### ISSUE TITLE
Feature Request: Delete User

### ISSUE THREAD

**Issue by danielfowler** [edalzell/statamic-profiler#15]
Nobody wants to have to email or call in to cancel an online account. Workshop has the `workshop:entry:delete` tag, so maybe there can be one added to Profiler?

**Comment by edalzell** [comment]
same params as the edit tag? i.e. it defaults to the current user, but you can pass in an `id` or `username`? @danielfowler

**Comment by danielfowler** [comment]
I think it’d be fine if deletion was for logged in user only, like Profiler is currently.
  
  
  

      
  
  
>   
>
>

**Comment by edalzell** [comment]
Too late already implemented
