### ISSUE TITLE
Feature Request: Edit Other User

### ISSUE THREAD

**Issue by danielfowler** [edalzell/statamic-profiler#16]
It would be great if Profiler could take a username or user ID for editing instead of defaulting to the currently logged-in user. In Workshop, an ID can be passed as a parameter to edit anything (except users).

It might look something like this: `{{ profiler:edit_form username="{ dude:username }" }}`

My use case is a self-service website where parents manage their kid(s) account(s). This feature would also be helpful for building frontend admin dashboards whereby user attributes might be edited more easily.

**Comment by edalzell** [comment]
how would set up the permissions so that people couldn't edit ALL other folks?

**Comment by danielfowler** [comment]
Well the rendered form tags gets hashed so there's not a risk of something just editing the source code with another username and editing someone they don't have permission to edit.

My use case enables users to enable a "profile assistant" who can then edit on their behalf, so I handle it with a handful of `{{ if }}` conditionals to make sure that the person's profile being edited has given explicit permission to the logged in user, or else the form doesn't even render.

**Comment by philpasquin** [comment]
Was this released? I would be interested in this feature as well, so family members can modify and sync their informations with their relatives.

Thank you

**Comment by edalzell** [comment]
Yup pass in `id` or `username` as a parameter
