### ISSUE TITLE
{{ success }} not set without redirect

### ISSUE THREAD

**Issue by robilim** [edalzell/statamic-profiler#19]
Hi @edalzell,

I've just installed the trial of your plugin and noticed that the template never receives `{{ success }}` if you do not set the redirect either the delete or edit forms. Assuming you coded based on the Workshop plugin, in their Controller they set `$this->flash->put('success', true);` after save or delete. Once I added this to your ProfilerController it worked as expected.

Thanks,
Rob

**Comment by edalzell** [comment]
Thanks @robilim I'll add that.
