### ISSUE TITLE
Validation for required field fails

### ISSUE THREAD

**Issue by aerni** [edalzell/statamic-profiler#24]
I've encountered another validation bug which is most likely related to #17 as well.

**Background**
I require the user to check a policy checkbox when registering with the `{{ user:register_form }}` tag.

```html
<input id="privacy_terms" type="checkbox" name="privacy_terms" value="accepted" required />
```

In my `user.yaml`:
```yaml
privacy_terms:
  type: checkboxes
  options:
    accepted: Accepted
  validate: 'required'
```

This checkbox is only shown on registration. It's not present in the profile update form using the `{{ profiler:edit_form }}` tag.

**The Bug**
When updating the profile picture of a user, the validation for this checkbox fails. But it only fails when updating the profile picture. It doesn't fail when updating any other field in the form.

My workaround, for now, is to have the checkbox present in the form but hide it.

```html
<input id="privacy_terms" type="checkbox" name="privacy_terms" value="accepted" required checked class="hidden" />
```

**Comment by danielfowler** [comment]
Man, for a long time I've just taken this as a feature (putting a hidden title+slug input on Workshop forms) not a bug. It would be nice to not have to embed hidden inputs to satisfy a required value.

**Comment by edalzell** [comment]
this is likely a user validation issue, not a profiler one.

However @aerni I plan to work on this addon this weekend, I'll get these issues all sorted.

**Comment by edalzell** [comment]
> Man, for a long time I've just taken this as a feature (putting a hidden title+slug input on Workshop forms) not a bug. It would be nice to not have to embed hidden inputs to satisfy a required value.

@danielfowler you DON'T want to provide a required value, when it's required? I'm confused at that. If the field is not required, don't set the validation on it to required?

**Comment by danielfowler** [comment]
I want it required when the input is on the page, but not otherwise.

Like @aerni points out, his privacy checkbox only exists at registration. When the user is editing their profile at any point later, the privacy checkbox doesn't exist in his code and therefore he doesn't want the Statamic `required` validation to run on that field.

**Comment by danielfowler** [comment]
My use case is a humanity check on user registration. Once they complete that, I never need to check again, but instead I have `<input type="hidden" name="humanity" value="correct_value"/>` on every template file where my users edit their profile.

**Comment by aerni** [comment]
That‘s exactly it. I really think it has to do with the assets validation bug because of this:

I have two routes. One to manage the user account with username and password. And another route to manage the profile with profile picture, name, address etc.

The validation for the required policy checkbox only fails on the profile page, where there‘s the assets failing assets validation.

Validation for the policy checkbox or any other required field doesn‘t fail on the account route.

**Comment by edalzell** [comment]
@danielfowler that sounds like a perfect solution to the issue. Can't have a required field that's only required on some requests and not others.

@aerni I'll look into all of those...

**Comment by edalzell** [comment]
@aerni like mentioned above you can't have a field that's only required some of the time, if it needs to be required, add it as a hidden field like you've done.

Please re-open if that is not the case.

**Comment by aerni** [comment]
I further explained this issue in #17. I think it's connected.
